### ISSUE TITLE
Report generation [HTML]

### ISSUE THREAD

**Issue by benlarsendk** [benlarsendk/PS03#14]
So far the only "report" generated is .txt-file with all used passwords and how much they are used. Could be awesome to generate some kind of HTML-report.

**Comment by benlarsendk** [comment]
Now generates a simple HTML report ( 991cd45a5d5df9fcba9c6de438a1e57d23a69f69 ). It still doesn't generate a report for WiFi's. Gonna need some refactoring :+1: It also has some weird percentages. See Issue #16 .

**Comment by benlarsendk** [comment]
Percentages fixed,

**Comment by dentych** [comment]
Wow, much talk to urself
